### ISSUE TITLE
[Request]: Additional configuration for torch function

### ISSUE THREAD

**Issue by lanman1** [cp2004/OctoPrint-WS281x_LED_Status#148]
### What would you like implemented?

My apologies if this is redundant as I posted this on a previous request, i just wasn't sure if it would be seen.

Until the additional multi segment functionality is determined, I would like to be able to configure the torch function to be able to call gcode.  This would allow standard caselights attached to the controller board to be used for case illumination using the very nice torch UI and scheduling/management.

### Why should this be implemented?

The positioning of 'bling' LEDs and interior lights are significantly different.  I know this will be addressed long term with multi segment configuration but until then, ad workaround may be to be able to call 'white illumination lights' separately from WS28xx strips.

**Comment by cp2004** [comment]
This plugin specifically controls WS281x LEDs over GPIO. It's a bit out of scope to start controlling LEDs via gcode, especially as a 'temporary' measure. More time spent implementing this one means less time implementing per-segment and other more in-scope features - and I would much much rather spend time doing this than other thigns.

There's a few other options for other kinds of LED control that may be of use to you, or it would be very simple to make this as a separate plugin - but I don't have capacity to make this plugin a one-size-fits-all. I encourage you to use code from this repository as inspiration but send gcode commands instead of directing it to the GPIO pins.

You can find some other LED plugins: https://plugins.octoprint.org/search/?q=led, maybe one of them will help your use case?
