### ISSUE TITLE
TM1804

### ISSUE THREAD

**Issue by Diaprojector** [cp2004/OctoPrint-WS281x_LED_Status#193]
### What would you like implemented?

Hi. It would be great if you added support for the TM1804 LED driver. 

### Why should this be implemented?

It runs on 24V, so it can be wired directly to most printer PSU's.

**Comment by cp2004** [comment]
I can't see a Python library available for those LEDs on a quick glance, which is what would be required as a driver for the LEDs - I can't implement the chip-specific driver code myself. If you know of one let me know (absolutely no guarantee that I would be able to do anything with it) otherwise I won't be adding support.
